#!/bin/bash
# Copyright (C) 2012 stieg
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301, USA.

PRFX="$(dirname $0)"

# Ensure we have sudo working.  Otherwise error out.
sudo true || (echo 'You must first setup sudo on your system.'; exit 1)

# So you can all see the commands.
set -x

sudo $PRFX/adb kill-server
sudo $PRFX/adb start-server
sudo $PRFX/adb usb
$PRFX/adb pull /system/app/Email.apk $PRFX/Email.apk.orig
$PRFX/adb remount
$PRFX/adb push $PRFX/Email-nosec.apk /system/app/Email.apk
$PRFX/adb sync
$PRFX/adb reboot